# Generated by Django 4.2.4 on 2024-06-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep_mantenimiento', '0003_alter_historialsolicitud_nuevo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialsolicitud',
            name='nuevo_status',
            field=models.CharField(choices=[('Rechazado', 'Rechazado'), ('Enviado', 'Enviado'), ('En_proceso', 'En proceso'), ('En_espera', 'En espera'), ('Realizado', 'Realizado'), ('Pendiente', 'Pendiente'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='status',
            field=models.CharField(blank=True, choices=[('Rechazado', 'Rechazado'), ('Enviado', 'Enviado'), ('En_proceso', 'En proceso'), ('En_espera', 'En espera'), ('Realizado', 'Realizado'), ('Pendiente', 'Pendiente'), ('Solicitud_Firmada', 'Firmado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_mantenimiento',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Herrería', 'Herrería'), ('Pintura', 'Pintura'), ('Pintarrón', 'Pintarrón'), ('Otro', 'Otro'), ('Plomería', 'Plomería'), ('Cerrajería', 'Cerrajería'), ('Cañones', 'Cañones'), ('Electrica', 'Electrica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='puesto',
            field=models.CharField(blank=True, choices=[('Secretario', 'Secretario/a'), ('Jefe', 'Jefe'), ('Subdirector', 'Subdirector/a'), ('Docente', 'Docente'), ('Empleado', 'Empleado')], max_length=100, null=True),
        ),
    ]
